### ISSUE TITLE
PHP Geocoder Provider

### ISSUE THREAD

**Issue by jbelien** [oSoc19/best#45]
There is the great [PHP Geocoder library](https://github.com/geocoder-php/Geocoder/). It's an abstraction layer on top of all the most used geocoding services.
I'm one of the maintainer of this project.

I'll create a Pelias provider (= abstraction layer) ASAP so people can easily query any Pelias based geocoding API including our own !

**Comment by JosseVanDelm** [comment]
That would be so nice! Thanks @jbelien

**Comment by jbelien** [comment]
Draft PR : https://github.com/geocoder-php/Geocoder/pull/982

**Comment by jbelien** [comment]
And here it is : https://packagist.org/packages/geo6/geocoder-php-best-provider 🍾
