### ISSUE TITLE
"File is not a zip file"

### ISSUE THREAD

**Issue by DenisValcke** [oSoc19/best#86]
When I try to use the project I keep running into the following error when running this command: `python /app/best/downloader/downloader.py /app/best/input --url https://opendata.bosa.be/download/best/best-full-latest.zip`:
```
Traceback (most recent call last):
  File "/app/best/downloader/downloader.py", line 105, in <module>
    unzip_recursive(args.file_name,args.output_dir,False)
  File "/app/best/downloader/downloader.py", line 32, in unzip_recursive
    with zipfile.ZipFile(zipped_file, 'r') as zfile:
  File "/usr/local/lib/python3.7/zipfile.py", line 1225, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.7/zipfile.py", line 1292, in _RealGetContents
    raise BadZipFile("File is not a zip file")
```

I've tried to run it locally on MacOS and in Docker but both give the same result. Is there something I might be overlooking here?

**Comment by barthanssens** [comment]
Hi, could you try again ? I was uploading a new version of the zip file, so the file might have been incomplete...

**Comment by DenisValcke** [comment]
Hi @barthanssens, thanks for your reply. That was indeed the problem, everything is working fine now. Thanks again, I wil close this issue now.

Have a great day!
