### ISSUE TITLE
I can't install pyproj.

### ISSUE THREAD

**Issue by haiduong87** [oSoc19/best#89]
If I install via pip install it gives

> Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\duongngh\appdata\local\programs\python\python37\python.exe' 'c:\users\duongngh\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\duongngh\AppData\Local\Temp\tmpxjumq7n8'
       cwd: C:\Users\duongngh\AppData\Local\Temp\pip-install-y6cywpcs\pyproj
  Complete output (1 lines):
  Proj executable not found. Please set PROJ_DIR variable.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\duongngh\appdata\local\programs\python\python37\python.exe' 'c:\users\duongngh\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\duongngh\AppData\Local\Temp\tmpxjumq7n8' Check the logs for full command output.

If can install via conda but the project doesn't recognize pyproj

**Comment by JosseVanDelm** [comment]
Hi there @haiduong87 ,

pyproj is a python wrapper for PROJ. So you should install that as well.
Try:
`conda install -c conda-forge proj4`
Other installation methods are covered here https://proj.org/install.html

Please let me know if this helps

**Comment by haiduong87** [comment]
Hi @JosseVanDelm 
I'm able to install pyproj but I can't run the convert script.
I got this, can you take a look?
>  File "C:\Users\haidu\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "e:\best-master\converter\converter.py", line 7, in <module>
    import pyproj
  File "C:\Users\haidu\AppData\Local\Programs\Python\Python37\lib\site-packages\pyproj\__init__.py", line 69, in <module>
    from pyproj._datadir import PYPROJ_CONTEXT
ImportError: DLL load failed: The specified module could not be found.

**Comment by JosseVanDelm** [comment]
Looks like pyproj package is not able to find some libraries (DLL's).
This probably means that you did not install the `PROJ` library where the pip (`pyproj`) package is looking for.
Maybe try removing the package with pip:
`pip remove pyproj`
And then try reinstalling `pyproj` with conda:
`condat install -c conda-forge pyproj`

I guess the reason for this error is that conda installs  packages in a virtual environment, and pip does not. The pyproj package is not installed in this virtual environment, and hence is looking for the wrong files.

Please let me know if this resolves your issue

**Comment by haiduong87** [comment]
Thanks @JosseVanDelm 
I can get it to work. I change to use Anaconda cmd for installing and I can convert the file.
Can you help  to me to verify the data (Python is new with me)
Is the converted csv (of all regions) is about 820 MB and has 5741585 lines?

**Comment by JosseVanDelm** [comment]
I think the numbers you mention seem about right! (@theodedeken can you back me up on this?).

@barthanssens it might be useful if we could (preferrably automatically on each update) publish these numbers (number of adresses and so on, maybe even per region?) and some other statistics on the bosa website or in a changelog on this github repo, so other people can perform these basic checks as well. Maybe we can even provide a hash of some kind ?

**Comment by barthanssens** [comment]
Good idea on publishing hash, I'll add it to my todo list. If all goes well, I'd be able to push this to production early October.
